# fly.toml app configuration file generated for mbv-blog on 2023-12-13T11:32:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mbv-blog"
primary_region = "ams"

[build]

[processes]
app = "./app"
worker = "./worker"

[http_service]
  processes = ["app"]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1

[[http_service.http_checks]]
  processes = ["app"]
  interval = 10000
  grace_period = "5s"
  method = "get"
  path = "/"
  protocol = "https"
  restart_limit = 0
  timeout = 2000
  tls_skip_verify = false

# [http_service]
#   internal_port = 8000
#   force_https = true
#   auto_stop_machines = true
#   auto_start_machines = true
#   min_machines_running = 1
#   processes = ["worker"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
