# fly.toml app configuration file generated for mbv-blog on 2023-12-13T11:32:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mbv-blog"
primary_region = "ams"

kill_signal = "SIGTERM"

[build]

[build.args]
app_host = "mortenvistisen.com"
app_scheme = "https"
is_ci = "true"

[processes]
app = "./app"
worker = "./worker"

[[services]]
  processes = ["worker"]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services.ports]]
  handlers = ["http"]
  port = 8000
  force_https = true  # optional

[http_service]
  processes = ["app"]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  processes = ["app"]
  interval = "30s"
  grace_period = "10s"
  method = "get"
  path = "/api/v1/health"
  protocol = "http"
  restart_limit = 0
  timeout = "5s"
  tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[vm]]
  size = 'shared-cpu-1x'
