title = "One Month One Dollar - Part one"
file_name = 'one-month-one-dollar-part-one'
description = 'A challenge to create a service within one month that makes more than one dollar'
tags = ['entrepreneurship', 'indiehacking', 'bootstrapping']
posted = '01/02/2023'
estimated_reading_time = 6
author = 'Morten Vistisen'
thumbnail = 'las-vegas.jpg'
order = 5
