title = 'A practical approach to structuring Golang applications'
file_name = 'practical-approach-to-structuring-go-apps'
description = 'A beginners guide to structuring Golang Apps'
tags = ['golang', 'domain-driven design', 'beginner', 'code-architecture']
posted = '30/01/2021'
estimated_reading_time = 12
author = 'Morten Vistisen'
thumbnail = 'go-logo-blue.png'
order = 1
