title = 'Wantrepreneurship & getting out of tutorial hell'
file_name = 'wantrepreneurship-getting-out-of-tutorial-hell '
description = 'Free-talk about wanting to be an entreprenuer and stopping to use tutorials'
tags = ['indiehacking', 'entreprenuership', 'wantrepreneurship', 'tutorials']
posted = '03/01/2023'
estimated_reading_time = 6
author = 'Morten Vistisen'
thumbnail = 'wantrepreneurship.jpg'
order = 4
