title = "One Month One Dollar - Part Two"
file_name = 'one-month-one-dollar-part-two'
description = 'A challenge to create a service within one month that makes more than one dollar'
tags = ['entrepreneurship', 'indiehacking', 'bootstrapping']
posted = '28/02/2023'
estimated_reading_time = 7
author = 'Morten Vistisen'
thumbnail = 'las-vegas.jpg'
order = 6
