name: fly deploy

on:
  push:
    branches:
      - master    # change to main if needed

jobs:
  migrate:
    name: migrate database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install just
        uses: taiki-e/install-action@just
        with:
          tool: just
      - name: run go setup
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: ./go.sum
          go-version: '1.22'
      - name: install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@v3.18.0
      - name: run migrations
        run: just up-migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DB_KIND: 'postgres'

  deploy:
    needs:
      - migrate
    name: deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --build-arg COMMIT_SHA=${{ github.sha }} --strategy bluegreen --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
